### ISSUE TITLE
Members Committee Positions

### ISSUE THREAD

**Issue by PKillackey** [haskins-io/Support#5]
When entering members details, the drop down menu for committee positions has incorrect information. The amendments required are for Men’s Captain and Ladies Captain. Currently the wording for both is Caption.

**Comment by haskins-io** [comment]
Thanks for pointing this out. I'll look into it and get it fixed

**Comment by haskins-io** [comment]
This has been fixed, and a new version of the app should be appearing in the relevant App Stores soon.
